* Purpose
~hex-game~ is a crate that implements the board game [[https://en.wikipedia.org/wiki/Hex_(board_game)][Hex]], in Rust.
* Warning
*Warning: This is still in development and is not ready for use yet.*
* Features
 - Reading and writing Hex games in the human-readable [[https://en.wikipedia.org/wiki/Smart_Game_Format][Smart Game Format]] (SGF) and additionally
   reading and writing games to a more efficient binary format
 - Playing Hex games using boards of any given size, including determining victory
 - Visualizing Hex games and boards
* Performance
Performance is a central goal of this crate: it will be used to train a neural network to play Hex,
and so at every point the goal is to make determining victory and playing moves as fast as possible.
* License
Licensed under either of

 - [[http://www.apache.org/licenses/LICENSE-2.0][Apache License, Version 2.0]]
 - [[http://opensource.org/licenses/MIT][MIT License]]

at your option.
* Plan
 - [ ] Disjoint-set structure for ~Board~
 - [ ] Basic ~Game~ struct
 - [ ] Serialization and deserialization to/from SGF
 - [ ] Binary format serialization and deserialization
 - [ ] Make board enums strings
* Contribution
Unless you explicitly state otherwise, any contribution intentionally submitted
for inclusion in the work by you, as defined in the Apache-2.0 license, shall be
dual licensed as above, without any additional terms or conditions.

